### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by geri-emp** [qtli/KEMP#5]

**Comment by geri-emp** [comment]
Thanks for make the code open. It is very helpful for me. But, I run the kemp_best checkpoint,  it doesn't work. I want to make sure that the checkpoint is really right? Because its size is only 27.2MB, so, I hope you can upload the true checkpoint.
![image](https://user-images.githubusercontent.com/46918035/165890665-03e50a49-93e9-470d-b64f-e5878fc51c47.png)
![image](https://user-images.githubusercontent.com/46918035/165890704-f473d18d-60c0-460e-adf0-736a96c4e2e9.png)

**Comment by qtli** [comment]
Hi, thanks so much for your information. Now I cannot access the server of the past. I retrain a checkpoint and substitue the crashed checkpoint file in the google drive.  Hope that helps.
