### ISSUE TITLE
Where is the "EmpatheticDialogue/sys_dialog_texts.train.npy"?

### ISSUE THREAD

**Issue by Deep1994** [qtli/KEMP#7]
Hi Qintong, I am so happy to see your great job! I have a question about the preprocess.py, I don't see the "EmpatheticDialogue/sys_dialog_texts.train.npy" or "EmpatheticDialogue/sys_dialog_texts.dev.npy" in the according file, where should I get these files? Thanks!

**Comment by Deep1994** [comment]
Oh, maybe data from [here](https://github.com/HLTCHKUST/MoEL/tree/master/empathetic-dialogue)?

**Comment by Deep1994** [comment]
Oh, I know, .npy format files can also store text, so it's all clear，nice work! Hope see you in AAAI 2023.

**Comment by lixx1024** [comment]
I still don't understand. Could you please explain in more detail how I can obtain these ".npy" format files?
