### ISSUE TITLE
Error issue in args:projection line 307 in code/KEMP.py file

### ISSUE THREAD

**Issue by asyrofist** [qtli/KEMP#9]
There's an issue for using running this code, that's said `argument namespace error` 
So I decided to non-active this line 307, there's no error after that..
```
if args.projection:
    self.embedding_proj_in = nn.Linear(args.emb_dim, args.hidden_dim, bias= False)
```

why does this happen?

**Comment by qtli** [comment]
Thanks for your comment. Please change the "project" argument to "projection" in the `main.py`. The argument name is got wrong.

**Comment by asyrofist** [comment]
Thank you for your response, Now It solved it..
